apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit323-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit323-k8s-app
  template:
    metadata:
      labels:
        app: sit323-k8s-app
    spec:
      containers:
      - name: sit323-k8s-app
        image: sit323-k8s-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
